// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGCRhIsfIm8lmLhY9NdJJZqSFoktsp5-k',
    appId: '1:50402832118:web:a584fc79f89a651a3cc6d7',
    messagingSenderId: '50402832118',
    projectId: 'social-wall-sancbyt',
    authDomain: 'social-wall-sancbyt.firebaseapp.com',
    storageBucket: 'social-wall-sancbyt.appspot.com',
    measurementId: 'G-X433YZJNLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG9nuDOV2Pasb6eS4iPN1SYJ4VvG10sJg',
    appId: '1:50402832118:android:4b066d6e46c199e83cc6d7',
    messagingSenderId: '50402832118',
    projectId: 'social-wall-sancbyt',
    storageBucket: 'social-wall-sancbyt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXf-PTJ3-45C-TBzqKJIeD76MBv9TeBDw',
    appId: '1:50402832118:ios:7ec855627699fff03cc6d7',
    messagingSenderId: '50402832118',
    projectId: 'social-wall-sancbyt',
    storageBucket: 'social-wall-sancbyt.appspot.com',
    iosBundleId: 'com.sancbyt.socialWall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXf-PTJ3-45C-TBzqKJIeD76MBv9TeBDw',
    appId: '1:50402832118:ios:7ec855627699fff03cc6d7',
    messagingSenderId: '50402832118',
    projectId: 'social-wall-sancbyt',
    storageBucket: 'social-wall-sancbyt.appspot.com',
    iosBundleId: 'com.sancbyt.socialWall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGCRhIsfIm8lmLhY9NdJJZqSFoktsp5-k',
    appId: '1:50402832118:web:e4e4a0830173acf53cc6d7',
    messagingSenderId: '50402832118',
    projectId: 'social-wall-sancbyt',
    authDomain: 'social-wall-sancbyt.firebaseapp.com',
    storageBucket: 'social-wall-sancbyt.appspot.com',
    measurementId: 'G-5MFDRYNEK8',
  );
}
